using System.Collections.Immutable;
using AdCodicem.ValueObjects.Generators.Internal;
using AdCodicem.ValueObjects.Generators.Model;

namespace AdCodicem.ValueObjects.Generators.Emit;

/// <summary>
/// Emits the per-assembly registration that publishes every generated value object to the runtime registry.
/// </summary>
/// <remarks>
/// A module initializer runs the registration the first time anything in the assembly is touched, which covers
/// the normal case without reflection and without dynamic code. <c>RegisterAll</c> stays public so that the
/// integrations can force it for an assembly they are about to enumerate by reflection alone — building an
/// EF Core model, for instance, may never touch a member of the assembly declaring the value objects.
/// </remarks>
internal static class RegistrationEmitter
{
    /// <summary>
    /// Emits the registration source for one assembly.
    /// </summary>
    /// <param name="models">Value objects declared in the assembly.</param>
    /// <param name="legacyJsonRegistry">
    /// Whether the assembly references AdCodicem.ValueObjects.Json, whose registry the converters are also published to.
    /// </param>
    /// <returns>The generated source.</returns>
    /// <remarks>
    /// <para>
    /// Each registration carries how to create the converter generated for the value object. The System.Text.Json
    /// generator cannot see the <c>[JsonConverter]</c> attribute emitted on the type, so a source-generated serializer
    /// context finds the converter through the descriptor instead, whatever this assembly references.
    /// </para>
    /// <para>
    /// An AdCodicem.ValueObjects.Json older than this generator reads only its own registry, which NuGet lets an
    /// application pair with a newer generator. Until the next major version, an assembly referencing the package
    /// therefore also publishes each converter the registration reaches there, as it always did.
    /// </para>
    /// </remarks>
    public static string Emit(ImmutableArray<ValueObjectModel> models, bool legacyJsonRegistry)
    {
        var writer = new CodeWriter();

        writer.Line("// <auto-generated/>");
        writer.Line("#nullable enable");
        writer.Line();
        writer.Open("namespace AdCodicem.ValueObjects.Generated");

        writer.Line("/// <summary>Publishes the value objects of this assembly to the runtime registry.</summary>");
        writer.Open("internal static class ValueObjectRegistration");

        writer.Line("private static int _registered;");
        writer.Line();

        writer.Line("/// <summary>Runs on first use of the assembly.</summary>");
        writer.Line("[global::System.Runtime.CompilerServices.ModuleInitializer]");
        writer.Line("internal static void Initialize() => RegisterAll();");
        writer.Line();

        writer.Line("/// <summary>Registers every value object of this assembly. Safe to call any number of times.</summary>");
        writer.Open("public static void RegisterAll()");
        writer.Open("if (global::System.Threading.Interlocked.Exchange(ref _registered, 1) != 0)");
        writer.Line("return;");
        writer.Close();
        writer.Line();

        foreach (var model in models)
        {
            writer.Line(model.RegistrationRoute.IsEmpty
                ? RegisterValueObject(model)
                : $"{model.RegistrationRoute.First()}.{StepClass(model, 0)}.Register();");
        }

        var identifiers = models
            .Where(static model => model.IsEntityId && model.RegistrationRoute.IsEmpty)
            .ToImmutableArray();
        if (identifiers.Length > 0)
        {
            writer.Line();
            writer.Line("// The reverse index, from a prefix to the type claiming it, is what lets AnyEntityId");
            writer.Line("// resolve an identifier whose type is only known once the text arrives.");
            foreach (var model in identifiers)
            {
                writer.Line(RegisterEntityId(model));
            }
        }

        var legacy = legacyJsonRegistry
            ? models.Where(static model => !model.IsGeneric && model.RegistrationRoute.IsEmpty).ToImmutableArray()
            : [];
        if (legacy.Length > 0)
        {
            writer.Line();
            writer.Line("// An AdCodicem.ValueObjects.Json older than this generator reads its own registry only.");
            foreach (var model in legacy)
            {
                writer.Line(
                    "global::AdCodicem.ValueObjects.Json.ValueObjectJsonRegistry.Register("
                    + $"new {model.QualifiedName}.ValueJsonConverter());");
            }
        }

        writer.Close();
        writer.Close();
        writer.Close();

        return writer.ToString();
    }

    /// <summary>
    /// Writes a step of the registration of a value object the registration of the assembly cannot see, as a class
    /// nested in one type of its route.
    /// </summary>
    /// <param name="writer">Writer, inside the declaration of the type at <paramref name="depth"/> on the route.</param>
    /// <param name="model">The value object.</param>
    /// <param name="depth">Position of the type on the route, from zero for the first.</param>
    /// <remarks>
    /// <para>
    /// A private or protected type is reachable only from the type declaring it, and from types nested in it. Each step
    /// therefore calls the next one, nested in a type it can see, and the last, nested in the type declaring the most
    /// deeply nested private or protected type, registers the value object.
    /// </para>
    /// <para>
    /// The step is a class of its own rather than a member of the author's type: calling a static member of a type runs
    /// its static constructor, which the registration must not do from the module initializer, and a class without
    /// static state has no initializer of its own to run. Its name carries its position on the route, so that a type of
    /// the route deriving from another one does not hide the step it inherits.
    /// </para>
    /// </remarks>
    public static void EmitStep(CodeWriter writer, ValueObjectModel model, int depth)
    {
        var route = model.RegistrationRoute.ToArray();

        writer.Line($"/// <summary>Registers <c>{model.TypeName}</c>, from a scope that can see it.</summary>");
        writer.Line("[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        writer.Open($"internal static class {StepClass(model, depth)}");
        writer.Line("/// <summary>Runs the step.</summary>");
        writer.Open("internal static void Register()");

        if (depth + 1 < route.Length)
        {
            writer.Line($"{route[depth + 1]}.{StepClass(model, depth + 1)}.Register();");
        }
        else
        {
            writer.Line(RegisterValueObject(model));
            if (model.IsEntityId)
            {
                writer.Line(RegisterEntityId(model));
            }
        }

        writer.Close();
        writer.Close();
        writer.Line();
    }

    /// <summary>
    /// Names the class holding the step of a value object's registration at a position on its route.
    /// </summary>
    private static string StepClass(ValueObjectModel model, int depth) => $"{model.RegistrationStep}_{depth}";

    /// <summary>
    /// Writes the statement registering a value object.
    /// </summary>
    /// <remarks>
    /// The converter is handed over as a factory, so that registering every value object of the assembly builds none:
    /// a converter is created the first time something asks the descriptor for it. A generic value object registers its
    /// definition, since the registration knows none of its constructions; the registry closes it over each one it is
    /// asked for.
    /// </remarks>
    private static string RegisterValueObject(ValueObjectModel model)
        => model.IsGeneric
            ? $"global::AdCodicem.ValueObjects.Metadata.ValueObjectRegistry.RegisterGenericDefinition(typeof({model.OpenQualifiedName}));"
            : "global::AdCodicem.ValueObjects.Metadata.ValueObjectRegistry.Register"
              + $"<{model.QualifiedName}, {model.UnderlyingFullName}>({model.QualifiedName}.Schema, static () => new {model.QualifiedName}.ValueJsonConverter());";

    private static string RegisterEntityId(ValueObjectModel model)
        => $"global::AdCodicem.ValueObjects.Identifiers.EntityIdRegistry.Register<{model.QualifiedName}>();";
}
