using System.Collections.Immutable;
using AdCodicem.ValueObjects.Generators.Internal;
using AdCodicem.ValueObjects.Generators.Model;

namespace AdCodicem.ValueObjects.Generators.Emit;

/// <summary>
/// Emits the per-assembly registration that publishes every generated value object to the runtime registry.
/// </summary>
/// <remarks>
/// A module initializer runs the registration the first time anything in the assembly is touched, which covers
/// the normal case without reflection and without dynamic code. <c>RegisterAll</c> stays public so that the
/// integrations can force it for an assembly they are about to enumerate by reflection alone — building an
/// EF Core model, for instance, may never touch a member of the assembly declaring the value objects.
/// </remarks>
internal static class RegistrationEmitter
{
    /// <summary>
    /// Emits the registration source for one assembly.
    /// </summary>
    /// <param name="models">Value objects declared in the assembly.</param>
    /// <param name="registerJsonConverters">
    /// Whether the AdCodicem.ValueObjects.Json package is referenced, in which case each generated converter is
    /// published so that a source-generated serializer context can find it.
    /// </param>
    /// <returns>The generated source.</returns>
    public static string Emit(ImmutableArray<ValueObjectModel> models, bool registerJsonConverters)
    {
        var writer = new CodeWriter();

        writer.Line("// <auto-generated/>");
        writer.Line("#nullable enable");
        writer.Line();
        writer.Open("namespace AdCodicem.ValueObjects.Generated");

        writer.Line("/// <summary>Publishes the value objects of this assembly to the runtime registry.</summary>");
        writer.Open("internal static class ValueObjectRegistration");

        writer.Line("private static int _registered;");
        writer.Line();

        writer.Line("/// <summary>Runs on first use of the assembly.</summary>");
        writer.Line("[global::System.Runtime.CompilerServices.ModuleInitializer]");
        writer.Line("internal static void Initialize() => RegisterAll();");
        writer.Line();

        writer.Line("/// <summary>Registers every value object of this assembly. Safe to call any number of times.</summary>");
        writer.Open("public static void RegisterAll()");
        writer.Open("if (global::System.Threading.Interlocked.Exchange(ref _registered, 1) != 0)");
        writer.Line("return;");
        writer.Close();
        writer.Line();

        foreach (var model in models)
        {
            writer.Line(
                "global::AdCodicem.ValueObjects.Metadata.ValueObjectRegistry.Register"
                + $"<{model.QualifiedName}, {model.UnderlyingFullName}>({model.QualifiedName}.Schema);");
        }

        var identifiers = models.Where(static model => model.IsEntityId).ToImmutableArray();
        if (identifiers.Length > 0)
        {
            writer.Line();
            writer.Line("// The reverse index, from a prefix to the type claiming it, is what lets AnyEntityId");
            writer.Line("// resolve an identifier whose type is only known once the text arrives.");
            foreach (var model in identifiers)
            {
                writer.Line(
                    "global::AdCodicem.ValueObjects.Identifiers.EntityIdRegistry.Register"
                    + $"<{model.QualifiedName}>();");
            }
        }

        if (registerJsonConverters)
        {
            writer.Line();
            writer.Line("// The System.Text.Json generator cannot see the [JsonConverter] attribute emitted above,");
            writer.Line("// so the converters are published for ValueObjectJsonConverterFactory to hand back.");
            foreach (var model in models)
            {
                writer.Line(
                    "global::AdCodicem.ValueObjects.Json.ValueObjectJsonRegistry.Register("
                    + $"new {model.QualifiedName}.ValueJsonConverter());");
            }
        }

        writer.Close();
        writer.Close();
        writer.Close();

        return writer.ToString();
    }
}
