using System;
using System.Collections.Generic;
using System.Linq;
using AdCodicem.ValueObjects.Generators.Internal;
using AdCodicem.ValueObjects.Generators.Model;

namespace AdCodicem.ValueObjects.Generators.Emit;

/// <summary>
/// Emits the implementation of one value object.
/// </summary>
internal static class ValueObjectEmitter
{
    private const string Abstractions = "global::AdCodicem.ValueObjects";
    private const string Identifiers = Abstractions + ".Identifiers";
    private const string IdFormat = Identifiers + ".EntityIdFormat";
    private const string ValidationResult = Abstractions + ".ValidationResult";
    private const string ErrorCodes = Abstractions + ".ValueObjectErrorCodes";
    private const string Inline = "[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]";
    private const string Invariant = "global::System.Globalization.CultureInfo.InvariantCulture";

    public static string Emit(ValueObjectModel model)
    {
        var writer = new CodeWriter();
        var underlying = model.Underlying;
        var value = underlying.FullName;
        var self = model.QualifiedName;

        writer.Line("// <auto-generated/>");
        writer.Line("#nullable enable");
        writer.Line("#pragma warning disable CS1591 // members are documented through <inheritdoc/>");
        writer.Line("#pragma warning disable CS8600, CS8601, CS8602, CS8603, CS8604 // the emitter proves the nullability itself");
        writer.Line();

        var closeCount = 0;
        if (model.Namespace.Length > 0)
        {
            writer.Open($"namespace {model.Namespace}");
            closeCount++;
        }

        foreach (var containing in model.ContainingTypes)
        {
            writer.Open(containing);
            closeCount++;
        }

        EmitTypeAttributes(writer, model);

        var contract = model switch
        {
            { IsEntityId: true } => $"{Identifiers}.IEntityId<{self}>",
            { Arithmetic: true } => $"{Abstractions}.INumericValueObject<{self}, {value}>",
            _ => $"{Abstractions}.IValueObject<{self}, {value}>",
        };

        writer.Open($"partial struct {model.TypeName} : {contract}");

        EmitState(writer, model, value, self);
        EmitEntityIdMembers(writer, model, self);

        // The named constants come before the schema so that the schema can publish their normalized values.
        EmitKnownValues(writer, model, value, self);
        EmitSchema(writer, model, underlying);
        EmitNormalize(writer, model, value);
        EmitValidate(writer, model, underlying, value);
        EmitFactories(writer, model, value, self);
        EmitEquality(writer, model, value, self);
        EmitComparison(writer, model, self);
        EmitFormatting(writer, model, underlying, value);
        EmitParsing(writer, model, underlying, value, self);
        EmitConversions(writer, model, value, self);
        EmitArithmetic(writer, model, underlying, value, self);

        JsonConverterEmitter.Emit(writer, model, underlying, value, self);
        TypeConverterEmitter.Emit(writer, model, underlying, value, self);

        writer.Close();

        for (var i = 0; i < closeCount; i++)
        {
            writer.Close();
        }

        return writer.ToString();
    }

    private static void EmitTypeAttributes(CodeWriter writer, ValueObjectModel model)
    {
        writer.Line($"[global::System.Text.Json.Serialization.JsonConverter(typeof({model.QualifiedName}.ValueJsonConverter))]");
        writer.Line($"[global::System.ComponentModel.TypeConverter(typeof({model.QualifiedName}.ValueTypeConverter))]");
        writer.Line("[global::System.Diagnostics.DebuggerDisplay(\"{ToString(),nq}\")]");
    }

    private static void EmitState(CodeWriter writer, ValueObjectModel model, string value, string self)
    {
        var underlying = model.Underlying;

        writer.Line("/// <summary>Backing storage. The struct is exactly the size of its underlying value.</summary>");
        writer.Line($"private readonly {value}{(underlying.IsReferenceType ? "?" : string.Empty)} _value;");
        writer.Line();

        writer.Line("/// <summary>Wraps an already normalized and validated value.</summary>");
        writer.Line(Inline);
        writer.Open($"private {model.TypeName}({value} value)");
        writer.Line("_value = value;");
        writer.Close();
        writer.Line();

        writer.Line("/// <inheritdoc />");
        writer.Line(underlying.IsReferenceType
            ? $"public {value} Value => _value ?? {value}.Empty;"
            : $"public {value} Value => _value;");
        writer.Line();

        writer.Line("/// <inheritdoc />");
        writer.Line(underlying.IsReferenceType
            ? "public bool IsDefault => _value is null;"
            : $"public bool IsDefault => _value.Equals(default({value}));");
        writer.Line();

        writer.Line("/// <inheritdoc />");
        writer.Line($"object? {Abstractions}.IValueObject.GetBoxedValue() => Value;");
        writer.Line();

        _ = self;
    }

    /// <summary>
    /// Emits the members an entity identifier adds over an ordinary string value object.
    /// </summary>
    /// <remarks>
    /// The profile is emitted as expression-bodied properties rather than initialized fields, so that the
    /// schema initializer below can read them regardless of the order the members appear in.
    /// </remarks>
    /// <param name="writer">Sink.</param>
    /// <param name="model">Value object being emitted.</param>
    /// <param name="self">Fully qualified name of the value object.</param>
    private static void EmitEntityIdMembers(CodeWriter writer, ValueObjectModel model, string self)
    {
        if (model.Id is not { } profile)
        {
            return;
        }

        var granularity = $"{Identifiers}.IdGranularity.{profile.GranularityName}";

        writer.Line("/// <inheritdoc />");
        writer.Line($"public static string Prefix => {LiteralFactory.Quote(profile.Prefix)};");
        writer.Line();

        writer.Line("/// <inheritdoc />");
        writer.Line($"public static {Identifiers}.IdGranularity Granularity => {granularity};");
        writer.Line();

        writer.Line("/// <inheritdoc />");
        writer.Line($"public static int Length => {profile.TotalLength};");
        writer.Line();

        writer.Line("/// <inheritdoc />");
        writer.Line(Inline);
        writer.Line($"public static {self} New() => New({Identifiers}.ValueObjectIds.TimeProvider, {Identifiers}.ValueObjectIds.Entropy);");
        writer.Line();

        // Straight to the constructor: what Create produces is canonical and valid by construction, so
        // re-normalizing and re-validating it would only cost a scan to reach the same value.
        writer.Line("/// <inheritdoc />");
        writer.Line($"public static {self} New(global::System.TimeProvider timeProvider, {Identifiers}.IdEntropySource entropy)");
        writer.Line($"    => new({IdFormat}.Create(Prefix, Granularity, timeProvider, entropy));");
        writer.Line();
    }

    private static void EmitSchema(CodeWriter writer, ValueObjectModel model, UnderlyingType underlying)
    {
        var properties = new List<string>();

        if (model.Pattern is not null)
        {
            properties.Add($"Pattern = {LiteralFactory.Quote(model.Pattern)},");
        }
        else if (model.IsEntityId)
        {
            // Published for the clients generated from the document, and never compiled here: at fixed length
            // over a fixed alphabet the running check is a span scan.
            properties.Add($"Pattern = {IdFormat}.SchemaPattern(Prefix, Granularity),");
        }

        if (model.MinLength >= 0)
        {
            properties.Add($"MinLength = {model.MinLength},");
        }

        if (model.MaxLength >= 0)
        {
            properties.Add($"MaxLength = {model.MaxLength},");
        }

        if (model.MinimumText is not null)
        {
            properties.Add($"Minimum = {LiteralFactory.Quote(model.MinimumText)},");
        }

        if (model.MaximumText is not null)
        {
            properties.Add($"Maximum = {LiteralFactory.Quote(model.MaximumText)},");
        }

        var format = model.SchemaFormat ?? underlying.SchemaFormat;
        if (format is not null)
        {
            properties.Add($"Format = {LiteralFactory.Quote(format)},");
        }

        if (model.Description is not null)
        {
            properties.Add($"Description = {LiteralFactory.Quote(model.Description)},");
        }

        if (model.Example is not null)
        {
            properties.Add($"Example = {LiteralFactory.Quote(model.Example)},");
        }
        else if (model.IsEntityId)
        {
            // Derived rather than random, so that regenerating the document produces the same bytes and a
            // committed specification does not churn on every build.
            properties.Add($"Example = {IdFormat}.Example(Prefix, Granularity),");
        }

        if (model.IsClosedValueSet)
        {
            properties.Add("IsClosedValueSet = true,");
        }

        if (!model.KnownValues.IsEmpty)
        {
            var boxed = string.Join(", ", model.KnownValues.Select(known => $"{known.Name}.Value"));
            properties.Add($"KnownValues = global::System.Collections.Immutable.ImmutableArray.Create<object>({boxed}),");
        }

        writer.Line("/// <summary>The declarative constraints of this value object, shared by validation, OpenAPI and persistence.</summary>");
        writer.Line($"public static global::AdCodicem.ValueObjects.Metadata.ValueObjectSchema Schema {{ get; }} = new()");
        writer.Line("{");
        writer.Indent();
        foreach (var property in properties)
        {
            writer.Line(property);
        }

        writer.Unindent();
        writer.Line("};");
        writer.Line();
    }

    private static void EmitKnownValues(CodeWriter writer, ValueObjectModel model, string value, string self)
    {
        if (model.KnownValues.IsEmpty)
        {
            return;
        }

        // Order matters: static initializers run in declaration order, and the membership lookup has to exist
        // before the named constants below go through Create, which consults it.
        if (model.IsClosedValueSet)
        {
            var normalized = string.Join(", ", model.KnownValues.Select(known => $"Normalize({known.Literal})"));
            var comparer = model.Underlying.IsString
                ? $", global::System.StringComparer.{model.ComparisonName}"
                : string.Empty;

            writer.Line("/// <summary>Frozen membership lookup backing the closed value set.</summary>");
            writer.Line($"private static readonly global::System.Collections.Frozen.FrozenSet<{value}> KnownUnderlyingValues =");
            writer.Line($"    global::System.Collections.Frozen.FrozenSet.ToFrozenSet(new {value}[] {{ {normalized} }}{comparer});");
            writer.Line();
        }

        foreach (var known in model.KnownValues)
        {
            // Create, not the raw constructor: a declared value that violates the type's own rules must fail
            // loudly on first use rather than exist as an unreachable constant.
            writer.Line($"/// <summary>{Xml(known.Description ?? known.Name)}</summary>");
            writer.Line($"public static {self} {known.Name} {{ get; }} = Create({known.Literal});");
            writer.Line();
        }

        var names = string.Join(", ", model.KnownValues.Select(known => known.Name));
        writer.Line("/// <summary>Every value declared through <c>[KnownValue]</c>, in declaration order.</summary>");
        writer.Line($"public static global::System.Collections.Immutable.ImmutableArray<{self}> KnownValues {{ get; }} =");
        writer.Line($"    global::System.Collections.Immutable.ImmutableArray.Create({names});");
        writer.Line();
    }

    private static void EmitNormalize(CodeWriter writer, ValueObjectModel model, string value)
    {
        writer.Line("/// <inheritdoc />");
        writer.Line(Inline);

        if (model.IsEntityId)
        {
            // The format owns its own canonical spelling — lower case, Crockford aliases — so an identifier
            // type never writes a normalizer, and VO0017 reports one that tried.
            writer.Line(
                $"public static {value} Normalize({value} value) => value is null "
                + $"? value : {IdFormat}.Normalize(global::System.MemoryExtensions.AsSpan(value), Prefix);");
        }
        else if (!model.HasNormalizeHook)
        {
            writer.Line($"public static {value} Normalize({value} value) => value;");
        }
        else if (model.Underlying.IsReferenceType)
        {
            // The hook never sees null: a missing value is rejected by Validate, not normalized into something.
            writer.Line($"public static {value} Normalize({value} value) => value is null ? value : NormalizeValue(value);");
        }
        else
        {
            writer.Line($"public static {value} Normalize({value} value) => NormalizeValue(value);");
        }

        writer.Line();
    }

    private static void EmitValidate(CodeWriter writer, ValueObjectModel model, UnderlyingType underlying, string value)
    {
        if (model.Pattern is not null)
        {
            // A generator cannot feed [GeneratedRegex], which only sees hand-written code, so the pattern is
            // compiled once into a static field instead. A timeout keeps a pathological pattern from hanging
            // a request thread.
            writer.Line("/// <summary>The declared pattern, compiled once for the lifetime of the process.</summary>");
            writer.Line("private static readonly global::System.Text.RegularExpressions.Regex DeclaredPattern = new(");
            writer.Line($"    {LiteralFactory.Quote(model.Pattern)},");
            writer.Line("    global::System.Text.RegularExpressions.RegexOptions.Compiled | global::System.Text.RegularExpressions.RegexOptions.CultureInvariant,");
            writer.Line("    global::System.TimeSpan.FromSeconds(1));");
            writer.Line();
        }

        writer.Line("/// <inheritdoc />");
        writer.Open($"public static {ValidationResult} Validate(in {value} value)");

        if (model.IsEntityId)
        {
            // An absent value reads as absent, not as a length violation, the same way it does for every other
            // string value object. A caller distinguishing "the field was not filled in" from "the field holds
            // something malformed" needs the two apart.
            writer.Open("if (value is null || value.Length == 0)");
            writer.Line($"return {ValidationResult}.Required(\"A value is required.\");");
            writer.Close();
            writer.Line();

            // The format reports which rule broke — length, prefix, alphabet or check character — rather than
            // flattening every rejection into one code a caller cannot act on.
            writer.Line($"var shape = {IdFormat}.Validate(global::System.MemoryExtensions.AsSpan(value), Prefix, Granularity);");
            writer.Open("if (!shape.IsValid)");
            writer.Line("return shape;");
            writer.Close();
            writer.Line();

            writer.Line(model.HasValidateHook
                ? "return ValidateValue(in value);"
                : $"return {ValidationResult}.Success;");

            writer.Close();
            writer.Line();
            return;
        }

        if (underlying.IsString)
        {
            writer.Open("if (value is null)");
            writer.Line($"return {ValidationResult}.Required(\"A value is required.\");");
            writer.Close();
            writer.Line();

            if (!model.AllowEmpty)
            {
                writer.Open("if (value.Length == 0)");
                writer.Line($"return {ValidationResult}.Required(\"The value must not be empty.\");");
                writer.Close();
                writer.Line();
            }

            if (model.MinLength >= 0)
            {
                writer.Open($"if (value.Length < {model.MinLength})");
                writer.Line($"return {ValidationResult}.Failure({ErrorCodes}.TooShort, \"The value must be at least {model.MinLength} characters long.\");");
                writer.Close();
                writer.Line();
            }

            if (model.MaxLength >= 0)
            {
                writer.Open($"if (value.Length > {model.MaxLength})");
                writer.Line($"return {ValidationResult}.Failure({ErrorCodes}.TooLong, \"The value must be at most {model.MaxLength} characters long.\");");
                writer.Close();
                writer.Line();
            }
        }

        if (model.Pattern is not null)
        {
            writer.Open("if (!DeclaredPattern.IsMatch(value))");
            writer.Line($"return {ValidationResult}.InvalidFormat(\"The value does not match the expected format.\");");
            writer.Close();
            writer.Line();
        }

        if (underlying.SupportsBounds && model.MinimumLiteral is not null)
        {
            writer.Open($"if (value < {model.MinimumLiteral})");
            writer.Line($"return {ValidationResult}.OutOfRange(\"The value must be greater than or equal to {Xml(model.MinimumText!)}.\");");
            writer.Close();
            writer.Line();
        }

        if (underlying.SupportsBounds && model.MaximumLiteral is not null)
        {
            writer.Open($"if (value > {model.MaximumLiteral})");
            writer.Line($"return {ValidationResult}.OutOfRange(\"The value must be less than or equal to {Xml(model.MaximumText!)}.\");");
            writer.Close();
            writer.Line();
        }

        if (model.IsClosedValueSet)
        {
            writer.Open("if (!KnownUnderlyingValues.Contains(value))");
            writer.Line($"return {ValidationResult}.Failure({ErrorCodes}.NotAKnownValue, \"The value is not one of the accepted values.\");");
            writer.Close();
            writer.Line();
        }

        writer.Line(model.HasValidateHook
            ? "return ValidateValue(in value);"
            : $"return {ValidationResult}.Success;");

        writer.Close();
        writer.Line();
    }

    private static void EmitFactories(CodeWriter writer, ValueObjectModel model, string value, string self)
    {
        writer.Line("/// <inheritdoc />");
        writer.Open($"public static {self} Create({value} value)");
        writer.Line("var normalized = Normalize(value);");
        writer.Line("var validation = Validate(in normalized);");
        writer.Open("if (!validation.IsValid)");
        writer.Line($"validation.ThrowIfInvalid(typeof({self}), value);");
        writer.Close();
        writer.Line();
        writer.Line($"return new {self}(normalized);");
        writer.Close();
        writer.Line();

        writer.Line("/// <inheritdoc />");
        writer.Line(Inline);
        writer.Line($"public static bool TryCreate({value} value, out {self} result) => TryCreate(value, out result, out _);");
        writer.Line();

        writer.Line("/// <inheritdoc />");
        writer.Open($"public static bool TryCreate({value} value, out {self} result, out {ValidationResult} validation)");
        writer.Line("var normalized = Normalize(value);");
        writer.Line("validation = Validate(in normalized);");
        writer.Open("if (validation.IsValid)");
        writer.Line($"result = new {self}(normalized);");
        writer.Line("return true;");
        writer.Close();
        writer.Line();
        writer.Line("result = default;");
        writer.Line("return false;");
        writer.Close();
        writer.Line();

        writer.Line("/// <inheritdoc />");
        writer.Line(Inline);
        writer.Line($"public static {self} CreateUnchecked({value} value) => new(value);");
        writer.Line();

        if (model.NormalizesFromSpan)
        {
            // Normalizing straight from the span means the normalized string is the only one allocated, where
            // going through TryCreate(string) would materialize the raw text first and then throw it away.
            writer.Line("/// <summary>Creates from text without materializing it before normalization.</summary>");
            writer.Open($"private static bool TryCreateFrom(global::System.ReadOnlySpan<char> value, out {self} result, out {ValidationResult} validation)");
            writer.Line(model.IsEntityId
                ? $"var normalized = {IdFormat}.Normalize(value, Prefix);"
                : "var normalized = NormalizeValue(value);");
            writer.Line("validation = Validate(in normalized);");
            writer.Open("if (validation.IsValid)");
            writer.Line($"result = new {self}(normalized);");
            writer.Line("return true;");
            writer.Close();
            writer.Line();
            writer.Line("result = default;");
            writer.Line("return false;");
            writer.Close();
            writer.Line();
        }
    }

    private static void EmitEquality(CodeWriter writer, ValueObjectModel model, string value, string self)
    {
        var underlying = model.Underlying;
        var comparison = $"global::System.StringComparison.{model.ComparisonName}";

        writer.Line("/// <inheritdoc />");
        writer.Line(Inline);
        writer.Line(underlying.IsString
            ? $"public bool Equals({self} other) => string.Equals(_value, other._value, {comparison});"
            : $"public bool Equals({self} other) => _value.Equals(other._value);");
        writer.Line();

        writer.Line("/// <inheritdoc />");
        writer.Line($"public override bool Equals(object? obj) => obj is {self} other && Equals(other);");
        writer.Line();

        writer.Line("/// <inheritdoc />");
        writer.Line(underlying.IsString
            ? $"public override int GetHashCode() => _value is null ? 0 : _value.GetHashCode({comparison});"
            : "public override int GetHashCode() => _value.GetHashCode();");
        writer.Line();

        writer.Line("/// <summary>Determines whether two values are equal.</summary>");
        writer.Line(Inline);
        writer.Line($"public static bool operator ==({self} left, {self} right) => left.Equals(right);");
        writer.Line();

        writer.Line("/// <summary>Determines whether two values differ.</summary>");
        writer.Line(Inline);
        writer.Line($"public static bool operator !=({self} left, {self} right) => !left.Equals(right);");
        writer.Line();

        _ = value;
    }

    private static void EmitComparison(CodeWriter writer, ValueObjectModel model, string self)
    {
        var comparison = $"global::System.StringComparison.{model.ComparisonName}";

        writer.Line("/// <inheritdoc />");
        writer.Line(model.Underlying.IsString
            ? $"public int CompareTo({self} other) => string.Compare(_value, other._value, {comparison});"
            : $"public int CompareTo({self} other) => _value.CompareTo(other._value);");
        writer.Line();

        foreach (var (op, test) in new[] { ("<", "< 0"), (">", "> 0"), ("<=", "<= 0"), (">=", ">= 0") })
        {
            writer.Line($"/// <summary>Compares two values.</summary>");
            writer.Line(Inline);
            writer.Line($"public static bool operator {op}({self} left, {self} right) => left.CompareTo(right) {test};");
            writer.Line();
        }
    }

    private static void EmitFormatting(CodeWriter writer, ValueObjectModel model, UnderlyingType underlying, string value)
    {
        writer.Line("/// <inheritdoc />");
        if (underlying.IsString)
        {
            writer.Line("public override string ToString() => Value;");
        }
        else if (underlying.IsSpanFormattable)
        {
            var format = underlying.RoundTripFormat is null ? "null" : LiteralFactory.Quote(underlying.RoundTripFormat);
            writer.Line($"public override string ToString() => Value.ToString({format}, {Invariant});");
        }
        else
        {
            writer.Line($"public override string ToString() => Value.ToString({Invariant});");
        }

        writer.Line();

        writer.Line("/// <inheritdoc />");
        if (model.HasFormatHook)
        {
            writer.Open("public string ToString(string? format, global::System.IFormatProvider? formatProvider)");
            writer.Line("var current = Value;");
            writer.Line($"return FormatValue(in current, global::System.MemoryExtensions.AsSpan(format), formatProvider ?? {Invariant});");
            writer.Close();
        }
        else if (model.HasTryFormatHook)
        {
            writer.Open("public string ToString(string? format, global::System.IFormatProvider? formatProvider)");
            writer.Line("var current = Value;");
            writer.Line($"var provider = formatProvider ?? {Invariant};");
            writer.Line($"global::System.Span<char> buffer = stackalloc char[{Math.Max(underlying.FormatBufferSize, 64)}];");
            writer.Open("if (TryFormatValue(in current, buffer, out var written, global::System.MemoryExtensions.AsSpan(format), provider))");
            writer.Line("return new string(buffer[..written]);");
            writer.Close();
            writer.Line();
            writer.Line("// The stack buffer was too small for this format: give the hook a destination it cannot outgrow.");
            writer.Line("var larger = new char[buffer.Length * 8];");
            writer.Line("return TryFormatValue(in current, larger, out written, global::System.MemoryExtensions.AsSpan(format), provider)");
            writer.Line("    ? new string(larger, 0, written)");
            writer.Line("    : ToString();");
            writer.Close();
        }
        else if (underlying.IsString)
        {
            writer.Line("public string ToString(string? format, global::System.IFormatProvider? formatProvider) => Value;");
        }
        else if (underlying.IsSpanFormattable)
        {
            writer.Line("public string ToString(string? format, global::System.IFormatProvider? formatProvider)");
            writer.Line($"    => Value.ToString(format, formatProvider ?? {Invariant});");
        }
        else
        {
            writer.Line("public string ToString(string? format, global::System.IFormatProvider? formatProvider)");
            writer.Line($"    => Value.ToString(formatProvider ?? {Invariant});");
        }

        writer.Line();

        writer.Line("/// <inheritdoc />");
        writer.Open("public bool TryFormat(global::System.Span<char> destination, out int charsWritten, global::System.ReadOnlySpan<char> format, global::System.IFormatProvider? provider)");

        if (model.HasTryFormatHook)
        {
            writer.Line("var current = Value;");
            writer.Line($"return TryFormatValue(in current, destination, out charsWritten, format, provider ?? {Invariant});");
        }
        else if (underlying.IsSpanFormattable)
        {
            writer.Line("var current = Value;");
            writer.Line($"return {Abstractions}.UnderlyingValue.TryFormat(in current, destination, out charsWritten, format, provider ?? {Invariant});");
        }
        else
        {
            writer.Line(underlying.IsString ? "var text = Value;" : $"var text = ToString(null, provider ?? {Invariant});");
            writer.Open("if (global::System.MemoryExtensions.AsSpan(text).TryCopyTo(destination))");
            writer.Line("charsWritten = text.Length;");
            writer.Line("return true;");
            writer.Close();
            writer.Line();
            writer.Line("charsWritten = 0;");
            writer.Line("return false;");
        }

        writer.Close();
        writer.Line();

        _ = value;
    }

    private static void EmitParsing(CodeWriter writer, ValueObjectModel model, UnderlyingType underlying, string value, string self)
    {
        writer.Line("/// <inheritdoc />");
        writer.Open($"public static {self} Parse(global::System.ReadOnlySpan<char> s, global::System.IFormatProvider? provider)");
        writer.Open("if (TryParse(s, provider, out var result))");
        writer.Line("return result;");
        writer.Close();
        writer.Line();
        writer.Line($"throw new {Abstractions}.ValueObjectException(");
        writer.Line($"    $\"'{{s.ToString()}}' is not a valid {model.TypeName}.\", typeof({self}), {ErrorCodes}.NotParsable, s.ToString());");
        writer.Close();
        writer.Line();

        writer.Line("/// <inheritdoc />");
        writer.Line(Inline);
        writer.Line($"public static {self} Parse(string s, global::System.IFormatProvider? provider) => Parse(global::System.MemoryExtensions.AsSpan(s), provider);");
        writer.Line();

        writer.Line("/// <inheritdoc cref=\"Parse(string, global::System.IFormatProvider?)\" />");
        writer.Line(Inline);
        writer.Line($"public static {self} Parse(string s) => Parse(global::System.MemoryExtensions.AsSpan(s), null);");
        writer.Line();

        writer.Line("/// <inheritdoc />");
        writer.Open($"public static bool TryParse(global::System.ReadOnlySpan<char> s, global::System.IFormatProvider? provider, out {self} result)");

        if (underlying.IsString)
        {
            writer.Line(model.NormalizesFromSpan
                ? "return TryCreateFrom(s, out result, out _);"
                : "return TryCreate(s.ToString(), out result);");
        }
        else if (underlying.Kind == UnderlyingKind.Char)
        {
            writer.Open("if (s.Length == 1)");
            writer.Line("return TryCreate(s[0], out result);");
            writer.Close();
            writer.Line();
            writer.Line("result = default;");
            writer.Line("return false;");
        }
        else if (underlying.Kind == UnderlyingKind.Boolean)
        {
            writer.Open("if (bool.TryParse(s, out var raw))");
            writer.Line("return TryCreate(raw, out result);");
            writer.Close();
            writer.Line();
            writer.Line("result = default;");
            writer.Line("return false;");
        }
        else
        {
            writer.Open($"if ({Abstractions}.UnderlyingValue.TryParse<{value}>(s, provider ?? {Invariant}, out var raw))");
            writer.Line("return TryCreate(raw, out result);");
            writer.Close();
            writer.Line();
            writer.Line("result = default;");
            writer.Line("return false;");
        }

        writer.Close();
        writer.Line();

        writer.Line("/// <inheritdoc />");
        writer.Open($"public static bool TryParse(global::System.ReadOnlySpan<char> s, global::System.IFormatProvider? provider, out {self} result, out {ValidationResult} validation)");

        if (underlying.IsString)
        {
            writer.Line(model.NormalizesFromSpan
                ? "return TryCreateFrom(s, out result, out validation);"
                : "return TryCreate(s.ToString(), out result, out validation);");
        }
        else
        {
            var parse = underlying.Kind switch
            {
                UnderlyingKind.Char => "s.Length == 1",
                UnderlyingKind.Boolean => "bool.TryParse(s, out raw)",
                _ => $"{Abstractions}.UnderlyingValue.TryParse<{value}>(s, provider ?? {Invariant}, out raw)",
            };

            writer.Line($"{value} raw = default;");
            writer.LineIf(underlying.Kind == UnderlyingKind.Char, "raw = s.Length == 1 ? s[0] : default;");
            writer.Open($"if (!({parse}))");
            writer.Line("result = default;");
            writer.Line($"validation = {ValidationResult}.Failure(");
            writer.Line($"    {ErrorCodes}.NotParsable,");
            writer.Line($"    \"The text is not a valid {underlying.Keyword}.\");");
            writer.Line("return false;");
            writer.Close();
            writer.Line();
            writer.Line("return TryCreate(raw, out result, out validation);");
        }

        writer.Close();
        writer.Line();

        writer.Line("/// <inheritdoc />");
        writer.Open($"public static bool TryParse(string? s, global::System.IFormatProvider? provider, out {self} result)");
        if (underlying.IsString)
        {
            writer.Line("return TryCreate(s!, out result);");
        }
        else
        {
            writer.Open("if (s is null)");
            writer.Line("result = default;");
            writer.Line("return false;");
            writer.Close();
            writer.Line();
            writer.Line("return TryParse(global::System.MemoryExtensions.AsSpan(s), provider, out result);");
        }

        writer.Close();
        writer.Line();

        writer.Line("/// <inheritdoc cref=\"TryParse(string, global::System.IFormatProvider?, out " + model.TypeName + ")\" />");
        writer.Line(Inline);
        writer.Line($"public static bool TryParse(string? s, out {self} result) => TryParse(s, null, out result);");
        writer.Line();

        writer.Line("/// <inheritdoc cref=\"TryParse(string, global::System.IFormatProvider?, out " + model.TypeName + ")\" />");
        writer.Line(Inline);
        writer.Line($"public static bool TryParse(global::System.ReadOnlySpan<char> s, out {self} result) => TryParse(s, null, out result);");
        writer.Line();
    }

    private static void EmitConversions(CodeWriter writer, ValueObjectModel model, string value, string self)
    {
        if (model.ImplicitConversionToValue)
        {
            writer.Line("/// <summary>Reads the underlying value.</summary>");
            writer.Line(Inline);
            writer.Line($"public static implicit operator {value}({self} valueObject) => valueObject.Value;");
            writer.Line();
        }

        if (!model.ExplicitConversionFromValue)
        {
            return;
        }

        writer.Line("/// <summary>Creates a value object, validating the value.</summary>");
        writer.Line(Inline);
        writer.Line($"public static explicit operator {self}({value} value) => Create(value);");
        writer.Line();
    }

    private static void EmitArithmetic(CodeWriter writer, ValueObjectModel model, UnderlyingType underlying, string value, string self)
    {
        if (!model.Arithmetic)
        {
            return;
        }

        // The narrow integer types promote to int under arithmetic, so the result needs a cast back. Every
        // integral operation is checked: a value object that silently wraps around is a value object that lies.
        var needsCast = underlying.Kind is UnderlyingKind.SByte or UnderlyingKind.Byte
            or UnderlyingKind.Int16 or UnderlyingKind.UInt16;
        var isIntegral = underlying.IsNumeric && underlying.Kind
            is not (UnderlyingKind.Decimal or UnderlyingKind.Double or UnderlyingKind.Single);

        string Result(string expression)
        {
            var cast = needsCast ? $"({underlying.Keyword})({expression})" : expression;
            return isIntegral ? $"checked({cast})" : cast;
        }

        EmitNumericConstants(writer, underlying, value, self, Result);

        writer.Line("/// <summary>Adds two values, validating the result.</summary>");
        writer.Line($"public static {self} operator +({self} left, {self} right) => Create({Result("left.Value + right.Value")});");
        writer.Line();

        writer.Line("/// <summary>Subtracts two values, validating the result.</summary>");
        writer.Line($"public static {self} operator -({self} left, {self} right) => Create({Result("left.Value - right.Value")});");
        writer.Line();

        writer.Line("/// <summary>Scales a value, validating the result.</summary>");
        writer.Line($"public static {self} operator *({self} left, {value} right) => Create({Result("left.Value * right")});");
        writer.Line();

        writer.Line("/// <summary>Scales a value, validating the result.</summary>");
        writer.Line($"public static {self} operator *({value} left, {self} right) => Create({Result("left * right.Value")});");
        writer.Line();

        writer.Line("/// <summary>Divides a value by a scalar, validating the result.</summary>");
        writer.Line($"public static {self} operator /({self} left, {value} right) => Create({Result("left.Value / right")});");
        writer.Line();

        writer.Line("/// <summary>Divides two values into a bare ratio, which carries no unit and is therefore not a value object.</summary>");
        writer.Line($"public static {value} operator /({self} left, {self} right) => {Result("left.Value / right.Value")};");
        writer.Line();

        if (!underlying.IsSigned)
        {
            return;
        }

        writer.Line("/// <summary>Negates a value, validating the result.</summary>");
        writer.Line($"public static {self} operator -({self} value) => Create({Result("-value.Value")});");
        writer.Line();
    }

    /// <summary>
    /// Emits concrete numeric helpers on the type itself.
    /// </summary>
    /// <remarks>
    /// <see cref="INumericValueObject{TSelf, TValue}"/> declares these as static virtual members with a default
    /// implementation, which C# only lets you reach through a type parameter. Emitting them here makes
    /// <c>Amount.Zero</c> and <c>Amount.Max(a, b)</c> ordinary code while still satisfying the interface, so the
    /// same value object serves both direct use and generic math.
    /// </remarks>
    private static void EmitNumericConstants(
        CodeWriter writer,
        UnderlyingType underlying,
        string value,
        string self,
        Func<string, string> result)
    {
        var bridge = $"{Abstractions}.UnderlyingValue";

        writer.Line("/// <summary>Gets the value representing zero.</summary>");
        writer.Line($"public static {self} Zero => Create({bridge}.Zero<{value}>());");
        writer.Line();

        writer.Line("/// <summary>Gets the value representing one.</summary>");
        writer.Line($"public static {self} One => Create({bridge}.One<{value}>());");
        writer.Line();

        writer.Line("/// <summary>Gets a value indicating whether the carried value is zero.</summary>");
        writer.Line($"public bool IsZero => {bridge}.IsZero(Value);");
        writer.Line();

        writer.Line("/// <summary>Returns the absolute value, validating the result.</summary>");
        writer.Line(underlying.IsSigned
            ? $"public static {self} Abs({self} value) => Create({bridge}.Abs(value.Value));"
            : $"public static {self} Abs({self} value) => value;");
        writer.Line();

        writer.Line("/// <summary>Returns the smaller of two values.</summary>");
        writer.Line($"public static {self} Min({self} left, {self} right) => left.CompareTo(right) <= 0 ? left : right;");
        writer.Line();

        writer.Line("/// <summary>Returns the larger of two values.</summary>");
        writer.Line($"public static {self} Max({self} left, {self} right) => left.CompareTo(right) >= 0 ? left : right;");
        writer.Line();

        writer.Line("/// <summary>Adds up a sequence, accumulating on the underlying type and validating once at the end.</summary>");
        writer.Open($"public static {self} Sum(global::System.Collections.Generic.IEnumerable<{self}> values)");
        writer.Line("global::System.ArgumentNullException.ThrowIfNull(values);");
        writer.Line();
        writer.Line($"var total = {bridge}.Zero<{value}>();");
        writer.Open("foreach (var current in values)");
        writer.Line($"total = {result("total + current.Value")};");
        writer.Close();
        writer.Line();
        writer.Line("return Create(total);");
        writer.Close();
        writer.Line();
    }

    internal static string Xml(string text)
        => text.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");
}
