<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>AdCodicem.ValueObjects.IntegrationTests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\samples\AdCodicem.ValueObjects.Sample.Api\AdCodicem.ValueObjects.Sample.Api.csproj" />
    <ProjectReference Include="..\..\src\AdCodicem.ValueObjects.EntityFrameworkCore\AdCodicem.ValueObjects.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\src\AdCodicem.ValueObjects.Dapper\AdCodicem.ValueObjects.Dapper.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="Testcontainers.MsSql" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Dapper" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="AdCodicem.ValueObjects" />
    <Using Include="AdCodicem.ValueObjects.Identifiers" />
    <Using Include="AdCodicem.ValueObjects.Sample.Api.Domain" />
    <Using Include="AdCodicem.ValueObjects.Sample.Api.Persistence" />
  </ItemGroup>

</Project>
