import fs from 'node:fs';
import path from 'node:path';
import {themes as prismThemes} from 'prism-react-renderer';
import type {Config, Plugin} from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

// The site is versioned (docs/adr/0005-version-the-documentation-site.md). website/docs/ is
// the preview: it describes main, and every merge that publishes a preview package redeploys
// it. Each stable release freezes it into versioned_docs/ through
// .github/scripts/docs-snapshot.sh, one entry per line of versions -- 0.3.x while the major is
// 0, 1.x from 1.0 on -- replaced in place when that line ships again.
function readJson<T>(file: string, fallback: T): T {
  const fullPath = path.join(__dirname, file);
  return fs.existsSync(fullPath) ? (JSON.parse(fs.readFileSync(fullPath, 'utf8')) as T) : fallback;
}

// Stable lines, newest first, as `docusaurus docs:version` records them. Absent until the
// first stable release.
const stableLines = readJson<string[]>('versions.json', []);
// The exact release each line was last frozen at: {"0.3.x": "0.3.2"}.
const releasedVersions = readJson<Record<string, string>>('released-versions.json', {});
const hasStable = stableLines.length > 0;

// deploy-docs.yml sets this from MinVer, so the preview names the package it describes. A local
// build has no published version to name.
const previewVersion = process.env.DOCS_PREVIEW_VERSION;
const previewLabel = previewVersion ? `Preview (${previewVersion})` : 'Preview';

const editRoot = 'https://github.com/AdCodicem/AdCodicem.ValueObjects/edit/main/website';

// The homepage is not versioned, but its example must describe what `dotnet add package`
// installs, so it is a partial that is frozen with the rest of the documentation and read from
// the latest stable snapshot. Before the first stable release there is none, and the preview is
// what the site serves by default anyway.
function homepageExample(): Plugin {
  const partial = '_homepage-example.md';
  const source = hasStable
    ? path.join(__dirname, 'versioned_docs', `version-${stableLines[0]}`, partial)
    : path.join(__dirname, 'docs', partial);
  // Falling back to docs/ here would quietly put unreleased code on the homepage, which is
  // exactly what reading the snapshot is for. A renamed partial has to wait for the next release.
  if (!fs.existsSync(source)) {
    throw new Error(`The homepage example ${path.relative(__dirname, source)} does not exist.`);
  }
  return {
    name: 'homepage-example',
    configureWebpack: () => ({resolve: {alias: {'@homepage-example': source}}}),
  };
}

const config: Config = {
  title: 'AdCodicem.ValueObjects',
  tagline: 'Single-value DDD value objects for .NET, with no reflection and no allocation on the paths that matter.',
  favicon: 'img/favicon.svg',

  future: {
    v4: true, // Improve compatibility with the upcoming Docusaurus v4
  },

  url: 'https://adcodicem.github.io',
  baseUrl: '/AdCodicem.ValueObjects/',

  organizationName: 'AdCodicem',
  projectName: 'AdCodicem.ValueObjects',

  onBrokenLinks: 'throw',
  markdown: {
    // The generated API reference under docs/api/ is full of bare generic
    // signatures -- ValueObjectContract<TValueObject, TValue> and the like --
    // which MDX parses as JSX and rejects. 'detect' keeps MDX for .mdx and
    // treats .md as CommonMark, where those are just text. None of the
    // hand-written pages use MDX features, so nothing is given up.
    format: 'detect',
    hooks: {
      onBrokenMarkdownLinks: 'throw',
    },
  },

  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },

  presets: [
    [
      'classic',
      {
        docs: {
          sidebarPath: './sidebars.ts',
          routeBasePath: 'docs',
          // A stable version's page edits its own snapshot under versioned_docs/, which is how a
          // misleading error in released documentation gets corrected. The API reference is
          // generated by DocFX, so there is nothing to edit: the fix belongs in the XML doc comment.
          editUrl: ({versionDocsDirPath, docPath}) =>
            docPath.startsWith('api/') ? undefined : `${editRoot}/${versionDocsDirPath}/${docPath}`,
          versions: {
            // Until a stable release exists the preview is the only version, so it is served at
            // /docs/ and the announcement bar below says so; the unreleased banner would only link
            // the reader to the page they are already on.
            current: {
              label: previewLabel,
              path: hasStable ? 'preview' : '',
              banner: hasStable ? 'unreleased' : 'none',
              badge: true,
              // Keeps search engines on the stable pages, which say the same thing about the
              // version people actually install.
              noIndex: hasStable,
            },
            ...Object.fromEntries(
              stableLines.map((line) => [
                line,
                {label: releasedVersions[line] ? `${line} (${releasedVersions[line]})` : line, badge: true},
              ]),
            ),
          },
        },
        blog: false,
        theme: {
          customCss: './src/css/custom.css',
        },
      } satisfies Preset.Options,
    ],
  ],

  plugins: [homepageExample],

  themeConfig: {
    colorMode: {
      respectPrefersColorScheme: true,
    },
    announcementBar: hasStable
      ? undefined
      : {
          id: 'no-stable-release',
          content:
            'No stable release yet: this documentation describes the latest preview' +
            (previewVersion ? `, <code>${previewVersion}</code>` : '') +
            '. Install it with <code>dotnet add package AdCodicem.ValueObjects --prerelease</code>.',
          isCloseable: false,
        },
    navbar: {
      title: 'AdCodicem.ValueObjects',
      items: [
        {
          type: 'docSidebar',
          sidebarId: 'docsSidebar',
          position: 'left',
          label: 'Docs',
        },
        {to: '/contributing', label: 'Contributing', position: 'left'},
        // Both appear with the first stable release: before it, the preview is the only version
        // and /docs/ already serves it.
        ...(hasStable
          ? [
              {
                to: '/docs/preview/introduction',
                label: 'Preview',
                position: 'right' as const,
                activeBaseRegex: '/docs/preview/',
              },
              {type: 'docsVersionDropdown', versions: stableLines, position: 'right' as const},
            ]
          : []),
        {
          href: 'https://www.nuget.org/packages/AdCodicem.ValueObjects',
          label: 'NuGet',
          position: 'right',
        },
        {
          href: 'https://github.com/AdCodicem/AdCodicem.ValueObjects',
          label: 'GitHub',
          position: 'right',
        },
      ],
    },
    footer: {
      style: 'dark',
      links: [
        {
          title: 'Docs',
          items: [
            {label: 'Introduction', to: '/docs/introduction'},
            {label: 'Getting Started', to: '/docs/getting-started'},
            {label: 'Packages', to: '/docs/packages'},
          ],
        },
        {
          title: 'More',
          items: [
            {label: 'Contributing', to: '/contributing'},
            {label: 'GitHub', href: 'https://github.com/AdCodicem/AdCodicem.ValueObjects'},
            {label: 'NuGet', href: 'https://www.nuget.org/packages/AdCodicem.ValueObjects'},
            {label: 'Issues', href: 'https://github.com/AdCodicem/AdCodicem.ValueObjects/issues'},
          ],
        },
      ],
      copyright: `Copyright © ${new Date().getFullYear()} AdCodicem. Released under the MIT licence.`,
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
      additionalLanguages: ['csharp', 'bash'],
    },
  } satisfies Preset.ThemeConfig,
};

export default config;
