import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'introduction',
    'getting-started',
    'packages',
    'authoring-guide',
    'design-decisions',
    'entity-identifiers',
    'testing',
    'benchmarks',
    {
      type: 'category',
      label: 'API reference',
      description: 'Generated from the XML doc comments in src/ by DocFX.',
      link: {type: 'generated-index', slug: '/api'},
      // Generated into website/docs/api/ and not committed; run `npm run docs:api`
      // (or dotnet docfx docs/docfx/docfx.json) before `npm start`.
      items: [{type: 'autogenerated', dirName: 'api'}],
    },
  ],
};

export default sidebars;
