import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

// Organized by what the reader is doing: learning (tutorials), solving a precise problem (how-to guides),
// looking something up (reference), or understanding why (explanation). The slugs of the pages that predate this
// layout are kept, because the navbar, the footer and the README link to them.
const sidebars: SidebarsConfig = {
  docsSidebar: [
    'introduction',
    {
      type: 'category',
      label: 'Tutorials',
      collapsed: false,
      items: [
        'getting-started',
        'tutorials/validation-and-normalization',
        'tutorials/known-values',
        'tutorials/request-to-database',
        'tutorials/public-identifiers',
      ],
    },
    {
      type: 'category',
      label: 'How-to guides',
      items: [
        'how-to/json',
        'how-to/xml',
        'how-to/aspnet-core',
        'how-to/openapi',
        'how-to/ef-core',
        'how-to/dapper',
        'how-to/mongodb',
        'how-to/fluentvalidation',
        'how-to/messaging',
        'how-to/logging',
        'how-to/azure',
        'how-to/mapping',
        'how-to/http-clients',
        'how-to/files-and-command-line',
        'how-to/string-comparison',
        'how-to/formatting',
        'how-to/conversions-and-arithmetic',
        'how-to/domain-members',
        'how-to/test-value-objects',
        'how-to/runtime-lookup',
        'how-to/ai-agents',
        'how-to/migrating',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        'packages',
        'authoring-guide',
        'reference/generated-members',
        'reference/errors',
        'reference/default-instances',
        'reference/diagnostics',
        {
          type: 'category',
          label: 'API reference',
          description: 'Generated from the XML doc comments in src/ by DocFX.',
          link: {type: 'generated-index', slug: '/api'},
          // Generated into website/docs/api/ and not committed; run `npm run docs:api`
          // (or dotnet docfx docs/docfx/docfx.json) before `npm start`.
          items: [{type: 'autogenerated', dirName: 'api'}],
        },
      ],
    },
    {
      type: 'category',
      label: 'Explanation',
      items: [
        'explanation/primitive-obsession',
        'design-decisions',
        'entity-identifiers',
        'benchmarks',
        'explanation/comparison',
        'testing',
      ],
    },
    'faq',
  ],
};

export default sidebars;
